/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6bc552d1-323c-4e65-a0b4-9056113ba6f2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qAjF4I3Xd",
    "aws_user_pools_web_client_id": "17vlhk1rqrm6p8kijcbhpaee1p",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-2",
            "search_indices": {
                "items": [
                    "deliveryPlace-dev"
                ],
                "default": "deliveryPlace-dev"
            }
        }
    }
};


export default awsmobile;
